name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: ['Release', 'Debug']

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Install Latest Stable CMake
      - name: Install CMake
        run: |
          choco install cmake --no-progress --installargs 'ADD_CMAKE_TO_PATH=System' -y
          cmake --version

      # Step 3: Configure Build
      - name: Configure $build_type Build
        run: |
          cmake -S . -B build/${{ matrix.build_type }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      # Step 4: Build
      - name: Build $build_type
        run: |
          cmake --build build/${{ matrix.build_type }} --config ${{ matrix.build_type }} --parallel
      
      # Step 6: Upload Artifacts
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nexus-${{ matrix.build_type }}-artifacts
          path: build/${{ matrix.build_type }}/*